--------------------------------------------------------
--  Fichier créé - lundi-décembre-28-2020   
--------------------------------------------------------
DROP TABLE "MARIEM"."ANNONCE" cascade constraints;
DROP TABLE "MARIEM"."RECLAMATION" cascade constraints;
--------------------------------------------------------
--  DDL for Table ANNONCE
--------------------------------------------------------

  CREATE TABLE "MARIEM"."ANNONCE" 
   (	"CODEAN" NUMBER, 
	"NOMAN" VARCHAR2(20 BYTE), 
	"DESCRIPTIONAN" VARCHAR2(100 BYTE), 
	"DATEAN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "MARIEM"."RECLAMATION" 
   (	"NUMREC" NUMBER, 
	"NOMREC" VARCHAR2(20 BYTE), 
	"DESCRIPTIONREC" VARCHAR2(100 BYTE), 
	"DATEREC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MARIEM.ANNONCE
SET DEFINE OFF;
REM INSERTING into MARIEM.RECLAMATION
SET DEFINE OFF;
Insert into MARIEM.RECLAMATION (NUMREC,NOMREC,DESCRIPTIONREC,DATEREC) values ('111111111','cdz','aaaaaaa','55 03 200');
--------------------------------------------------------
--  DDL for Index ANNONCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARIEM"."ANNONCE_PK" ON "MARIEM"."ANNONCE" ("CODEAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARIEM"."RECLAMATION_PK" ON "MARIEM"."RECLAMATION" ("NUMREC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANNONCE
--------------------------------------------------------

  ALTER TABLE "MARIEM"."ANNONCE" ADD CONSTRAINT "ANNONCE_PK" PRIMARY KEY ("CODEAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MARIEM"."ANNONCE" MODIFY ("CODEAN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "MARIEM"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("NUMREC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MARIEM"."RECLAMATION" MODIFY ("NUMREC" NOT NULL ENABLE);
